// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Lukextensions
{
    internal sealed partial class Vsix
    {
        public const string Id = "Lukextensions.4d3d1560-97e9-427b-9d92-caacb8e5b4a3";
        public const string Name = "Lukextensions";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
