// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Lukextensions
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string LukextensionsString = "c90157a0-b4ca-4656-a7d9-65bdd192db28";
        public static Guid Lukextensions = new Guid(LukextensionsString);

        public const string CommonString = "014e1fff-1690-49c4-922c-8402d6637357";
        public static Guid Common = new Guid(CommonString);

        public const string CloudRemoverString = "77e1278a-4b61-44c7-8b5b-fec628dbb58f";
        public static Guid CloudRemover = new Guid(CloudRemoverString);

        public const string SharepointString = "8270cc16-7d74-4ae5-8719-cf8ed5300b35";
        public static Guid Sharepoint = new Guid(SharepointString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int RootGroup = 0x0001;
        public const int RootMenu = 0x0002;
        public const int NamespacesGroup = 0x0100;
        public const int CommonMenu = 0x0101;
        public const int CommonNamespace = 0x0102;
        public const int CloudRemoverMenu = 0x0103;
        public const int CloudRemoverNamespace = 0x0104;
        public const int SharepointMenu = 0x0105;
        public const int SharepointNamespace = 0x0106;
        public const int TuppleAliasMapper = 0x006D;
        public const int RemoveTenants = 0x0074;
        public const int UndoThis = 0x0075;
        public const int MigrateToSharepoint = 0x006E;
        public const int OpenSettings = 0x006F;
    }
}